-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- 1. Table for Academic Sources (Theses, Papers, Journals)
create table if not exists public.academic_papers (
  id bigint generated by default as identity primary key,
  title text not null,
  authors text,
  university text, -- 'Oxford', 'Harvard', 'MIT', 'Stanford'
  published_date date,
  pdf_url text,
  topic_tags text[], -- ['Market Microstructure', 'High Frequency Trading']
  citation_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table for High-Density Embeddings (The Knowledge)
-- We use 3072 dimensions for OpenAI 'text-embedding-3-large'
create table if not exists public.academic_chunks (
  id bigint generated by default as identity primary key,
  paper_id bigint references public.academic_papers(id) on delete cascade,
  content text, -- The actual text chunk (theorem, formula explanation)
  embedding vector(3072), -- HIGH DENSITY VECTOR
  similarity_threshold float default 0.0
);

-- 3. Table for "Validated Alpha" (Extracted Strategies)
create table if not exists public.academic_alpha (
  id bigint generated by default as identity primary key,
  strategy_name text not null, -- e.g. "VPIN Flow Toxicity"
  origin_paper_id bigint references public.academic_papers(id),
  math_formula text, -- LaTeX or Text description of formula
  code_snippet text, -- Python implementation
  risk_profile text, -- 'Low', 'Medium', 'High'
  win_rate_theoretical float,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Function to Match Signals against Academic Knowledge
create or replace function match_academic_knowledge (
  query_embedding vector(3072),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  title text,
  university text,
  similarity float
)
)
language plpgsql
security definer -- (Optional but often good for RPCs, though not strictly required for search_path fix)
set search_path = public, extensions
as $$
begin
  return query(
    select
      ac.id,
      ac.content,
      ap.title,
      ap.university,
      1 - (ac.embedding <=> query_embedding) as similarity
    from
      public.academic_chunks ac
    join
      public.academic_papers ap on ac.paper_id = ap.id
    where
      1 - (ac.embedding <=> query_embedding) > match_threshold
    order by
      ac.embedding <=> query_embedding
    limit
      match_count
  );
end;
$$;

-- RLS Policies (Open Read for Bot, Service Role Write)
alter table public.academic_papers enable row level security;
alter table public.academic_chunks enable row level security;
alter table public.academic_alpha enable row level security;

create policy "Service Role can manage papers"
  on public.academic_papers for all
  using ( auth.role() = 'service_role' );

create policy "Service Role can manage chunks"
  on public.academic_chunks for all
  using ( auth.role() = 'service_role' );

create policy "Public/Bot can read papers"
  on public.academic_papers for select
  using ( true );

create policy "Public/Bot can read chunks"
  on public.academic_chunks for select
  using ( true );

create policy "Service Role can manage alpha"
  on public.academic_alpha for all
  using ( auth.role() = 'service_role' );

create policy "Public/Bot can read alpha"
  on public.academic_alpha for select
  using ( true );
