-- Phase 37: Audit History Schema
-- Stores the final result of every signal for the Investor Dashboard

CREATE TABLE IF NOT EXISTS public.signal_audit_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT REFERENCES public.signals(id) ON DELETE CASCADE,
    symbol TEXT NOT NULL,
    signal_type TEXT NOT NULL, -- BUY/SELL
    entry_price NUMERIC NOT NULL,
    exit_price NUMERIC, -- Price at closure (TP/SL or Manual)
    outcome TEXT CHECK (outcome IN ('WIN', 'LOSS', 'BREAKEVEN', 'PENDING')),
    pnl_percent NUMERIC, -- Realized PnL %
    max_drawdown_pct NUMERIC, -- Worst point during trade
    max_profit_pct NUMERIC, -- Best point during trade
    duration_minutes INT,
    audit_timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: Public Read, Service Write
ALTER TABLE public.signal_audit_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Audit"
    ON public.signal_audit_history FOR SELECT
    USING (true);

CREATE POLICY "Service Write Audit"
    ON public.signal_audit_history FOR ALL
    USING ((select auth.role()) = 'service_role');
