-- Create table for AI Oracle Insights (Neural Link)
CREATE TABLE IF NOT EXISTS public.oracle_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    symbol TEXT NOT NULL,
    trend_status TEXT NOT NULL CHECK (trend_status IN ('BULLISH', 'BEARISH', 'NEUTRAL')),
    ai_probability FLOAT NOT NULL,
    reasoning TEXT,
    technical_context JSONB DEFAULT '{}'::JSONB
);

-- Enable RLS
ALTER TABLE public.oracle_insights ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users can read
CREATE POLICY "Enable read access for authenticated users" 
ON public.oracle_insights FOR SELECT 
TO authenticated, service_role 
USING (true);

-- Policy: Only service_role can insert (AI Engine)
CREATE POLICY "Enable insert for service_role only" 
ON public.oracle_insights FOR INSERT 
TO service_role 
WITH CHECK (true);

-- Notify Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE oracle_insights;

-- Create AI Model Registry (Neural Link Metadata)
CREATE TABLE IF NOT EXISTS public.ai_model_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_tag TEXT NOT NULL,
    accuracy FLOAT NOT NULL,
    samples_trained INT,
    features_used JSONB,
    last_bootstrap_at TIMESTAMPTZ DEFAULT NOW(),
    active BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.ai_model_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for authenticated" ON public.ai_model_registry FOR SELECT TO authenticated, service_role USING (true);
CREATE POLICY "Enable insert for service_role" ON public.ai_model_registry FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "Enable update for service_role" ON public.ai_model_registry FOR UPDATE TO service_role USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE ai_model_registry;
