-- Nexus V2 Strict Schema Initialization (Robust Refresh)
-- Run this in the Supabase SQL Editor

-- 1. Create 'signals' table
CREATE TABLE IF NOT EXISTS public.signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pair TEXT NOT NULL,
    direction TEXT CHECK (direction IN ('LONG', 'SHORT')),
    entry_price NUMERIC,
    tp_price NUMERIC,
    sl_price NUMERIC,
    ai_confidence NUMERIC,
    risk_level TEXT CHECK (risk_level IN ('LOW', 'MID', 'HIGH')),
    status TEXT DEFAULT 'ACTIVE',
    result_pnl NUMERIC DEFAULT 0,
    rsi NUMERIC,
    atr_value NUMERIC,
    volume_ratio NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create 'paper_trades' table
CREATE TABLE IF NOT EXISTS public.paper_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT REFERENCES public.signals(id),
    entry_price_executed NUMERIC,
    exit_price_executed NUMERIC,
    realized_pnl NUMERIC,
    bot_status TEXT DEFAULT 'OPEN',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create 'paper_positions' table
CREATE TABLE IF NOT EXISTS public.paper_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    entry_price NUMERIC,
    quantity NUMERIC,
    status TEXT DEFAULT 'OPEN',
    pnl NUMERIC,
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    bot_stop_loss NUMERIC,
    bot_take_profit NUMERIC,
    leverage NUMERIC,
    liquidation_price NUMERIC,
    initial_margin NUMERIC,
    signal_id BIGINT REFERENCES public.signals(id)
);

-- 4. AGGRESSIVE MIGRATION (Ensures relationship exists even if table was old)
DO $$ 
BEGIN 
    -- 1. Add signal_id column if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='paper_positions' AND column_name='signal_id') THEN
        ALTER TABLE public.paper_positions ADD COLUMN signal_id BIGINT;
    END IF;

    -- 2. Drop old constraint if exists (from market_signals or old name)
    ALTER TABLE public.paper_positions DROP CONSTRAINT IF EXISTS paper_positions_market_signals_id_fkey;
    ALTER TABLE public.paper_positions DROP CONSTRAINT IF EXISTS paper_positions_signal_id_fkey;

    -- 3. Add fresh constraint to 'signals' table
    ALTER TABLE public.paper_positions 
    ADD CONSTRAINT paper_positions_signal_id_fkey 
    FOREIGN KEY (signal_id) REFERENCES public.signals(id);

    -- 4. Data Migration (Optional: try to link existing entries if they had market_signals_id)
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='paper_positions' AND column_name='market_signals_id') THEN
        UPDATE public.paper_positions SET signal_id = market_signals_id WHERE signal_id IS NULL;
    END IF;

    -- Add missing columns to signals if they don't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='signals' AND column_name='rsi') THEN
        ALTER TABLE public.signals ADD COLUMN rsi NUMERIC;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='signals' AND column_name='atr_value') THEN
        ALTER TABLE public.signals ADD COLUMN atr_value NUMERIC;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='signals' AND column_name='volume_ratio') THEN
        ALTER TABLE public.signals ADD COLUMN volume_ratio NUMERIC;
    END IF;
END $$;

-- 5. Enable RLS and Policies (Idempotent)
ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Signals" ON public.signals;
CREATE POLICY "Public Read Signals" ON public.signals FOR SELECT USING (true);
DROP POLICY IF EXISTS "Service Role Write Signals" ON public.signals;
CREATE POLICY "Service Role Write Signals" ON public.signals FOR ALL USING (true); 

ALTER TABLE public.paper_trades ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Trades" ON public.paper_trades;
CREATE POLICY "Public Read Trades" ON public.paper_trades FOR SELECT USING (true);

ALTER TABLE public.paper_positions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Positions" ON public.paper_positions;
CREATE POLICY "Public Read Positions" ON public.paper_positions FOR SELECT USING (true);

-- 6. REALTIME (Idempotent)
DO $$
BEGIN
    INSERT INTO _realtime.publication_tables (publication_name, schema_name, table_name)
    VALUES ('supabase_realtime', 'public', 'signals'),
           ('supabase_realtime', 'public', 'paper_trades'),
           ('supabase_realtime', 'public', 'paper_positions')
    ON CONFLICT DO NOTHING;
EXCEPTION WHEN OTHERS THEN
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.signals; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.paper_trades; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.paper_positions; EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;
