-- Nexus V2 Strict Schema Initialization
-- Run this in the Supabase SQL Editor

-- 1. Create 'signals' table (The Source of Truth)
CREATE TABLE IF NOT EXISTS public.signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pair TEXT NOT NULL,
    direction TEXT CHECK (direction IN ('LONG', 'SHORT')),
    entry_price NUMERIC,
    tp_price NUMERIC,
    sl_price NUMERIC,
    ai_confidence NUMERIC,
    risk_level TEXT CHECK (risk_level IN ('LOW', 'MID', 'HIGH')),
    status TEXT DEFAULT 'ACTIVE', -- ACTIVE, CLOSED, CANCELLED
    result_pnl NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create 'paper_trades' table (The Execution Log)
CREATE TABLE IF NOT EXISTS public.paper_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT REFERENCES public.signals(id),
    entry_price_executed NUMERIC,
    exit_price_executed NUMERIC,
    realized_pnl NUMERIC,
    bot_status TEXT DEFAULT 'OPEN', -- OPEN, CLOSED
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable RLS (Optional but recommended, allow Anon read for Frontend)
ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Signals" ON public.signals FOR SELECT USING (true);
CREATE POLICY "Service Role Write Signals" ON public.signals FOR ALL USING (true); 

ALTER TABLE public.paper_trades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Trades" ON public.paper_trades FOR SELECT USING (true);

-- 4. REALTIME CONFIGURATION FIX (Solves 'realtime.list_changes' errors)
-- Ensure these tables are available for Realtime subscription
ALTER PUBLICATION supabase_realtime ADD TABLE public.signals;
ALTER PUBLICATION supabase_realtime ADD TABLE public.paper_trades;
ALTER PUBLICATION supabase_realtime ADD TABLE public.paper_positions;

-- If 'paper_positions' doesn't exist, create it (Legacy Support)
CREATE TABLE IF NOT EXISTS public.paper_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    entry_price NUMERIC,
    quantity NUMERIC,
    status TEXT DEFAULT 'OPEN',
    pnl NUMERIC,
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    bot_stop_loss NUMERIC,
    bot_take_profit NUMERIC,
    leverage NUMERIC,
    liquidation_price NUMERIC,
    initial_margin NUMERIC,
    market_signals_id BIGINT REFERENCES public.signals(id) -- Optional link
);
ALTER PUBLICATION supabase_realtime ADD TABLE public.paper_positions;
