-- Nexus Data Vault: Proprietary Time-Series Storage
-- Stores raw on-chain metrics bypassed from aggregation APIs

CREATE TABLE IF NOT EXISTS public.nexus_data_vault (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    symbol TEXT NOT NULL,
    price NUMERIC NOT NULL,
    liquidity NUMERIC,
    nli_score NUMERIC DEFAULT 1.0,
    source TEXT DEFAULT 'HELIUS_RAW',
    meta JSONB
);

-- Enable RLS
ALTER TABLE public.nexus_data_vault ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public Read Vault" ON public.nexus_data_vault FOR SELECT USING (true);
CREATE POLICY "Service Role Write Vault" ON public.nexus_data_vault FOR INSERT WITH CHECK (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_vault_symbol ON public.nexus_data_vault(symbol);
CREATE INDEX IF NOT EXISTS idx_vault_timestamp ON public.nexus_data_vault(timestamp DESC);

-- Real-time
ALTER PUBLICATION supabase_realtime ADD TABLE public.nexus_data_vault;
