
-- PAPER TRADING BOT SETUP (SECURE V2)
-- Run this in Supabase SQL Editor

-- 1. Create table for positions (if not exists)
create table if not exists paper_positions (
    id bigint generated by default as identity primary key,
    signal_id bigint references market_signals(id),
    symbol text not null,
    entry_price numeric not null,
    quantity numeric not null,
    status text not null default 'OPEN', -- OPEN, CLOSED, LIQUIDATED
    pnl numeric,
    exit_price numeric,
    exit_reason text, -- TP, SL, MANUAL
    opened_at timestamp with time zone default timezone('utc'::text, now()) not null,
    closed_at timestamp with time zone
);

-- 2. Enable RLS
alter table paper_positions enable row level security;

-- 3. FIX POLICIES (DROP UNSAFE, ADD SECURE)

-- Drop the dangerous "allow all" policy if it exists
drop policy if exists "Enable all access for service role" on paper_positions;
drop policy if exists "Public Read Access" on paper_positions;

-- Create PUBLIC READ ONLY policy (Allows Frontend to view stats)
create policy "Public Read Access" on paper_positions
    for select
    to anon, authenticated, service_role
    using (true);

-- (NOTE: The Service Role Key bypasses RLS automatically, 
-- so no explicit Write policy is needed for the backend. 
-- Public cannot write/delete.)

-- 4. Enable Realtime
-- 4. Enable Realtime (Idempotent Check)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'paper_positions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE paper_positions;
  END IF;
END $$;

-- Notify
NOTIFY pgrst, 'reload config';
