
-- PAPER TRADING BOT SETUP
-- Run this in Supabase SQL Editor

-- 1. Create table for positions
create table if not exists paper_positions (
    id bigint generated by default as identity primary key,
    signal_id bigint references market_signals(id),
    symbol text not null,
    entry_price numeric not null,
    quantity numeric not null,
    status text not null default 'OPEN', -- OPEN, CLOSED, LIQUIDATED
    pnl numeric,
    exit_price numeric,
    exit_reason text, -- TP, SL, MANUAL
    opened_at timestamp with time zone default timezone('utc'::text, now()) not null,
    closed_at timestamp with time zone
);

-- 2. Enable RLS
alter table paper_positions enable row level security;

-- 3. Create Policy (Allow all for Service Role / authenticated)
create policy "Enable all access for service role" on paper_positions
    for all using (true) with check (true);

-- 4. Enable Realtime
alter publication supabase_realtime add table paper_positions;

-- Notify
NOTIFY pgrst, 'reload config';
