-- 1. Create Payment Logs Table
-- Tracks incoming blockchain transactions to prevent double-crediting
CREATE TABLE IF NOT EXISTS public.payment_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_hash TEXT NOT NULL UNIQUE,
    sender_address TEXT,
    amount NUMERIC,
    currency TEXT DEFAULT 'USDT',
    status TEXT DEFAULT 'PROCESSED', -- PROCESSED, FAILED
    user_id UUID REFERENCES auth.users(id), -- Optional: Link if we can identify sender
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE public.payment_logs ENABLE ROW LEVEL SECURITY;

-- 3. Security Policies (Strict Backend Only)
-- No public read access. Only Service Role (Worker) can Insert/Select.
DROP POLICY IF EXISTS "Service Role Full Access Payments" ON public.payment_logs;
CREATE POLICY "Service Role Full Access Payments" ON public.payment_logs
FOR ALL TO service_role
USING (true);

-- 4. Realtime (Optional, for admin dashboard)
DO $$
BEGIN
  INSERT INTO _realtime.publication_tables (publication_name, schema_name, table_name)
  VALUES ('supabase_realtime', 'public', 'payment_logs')
  ON CONFLICT DO NOTHING;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;
