-- Phase 38: User Profile & Trade Journal Schema
-- Use this to upgrade the Profiles table and add the Journal feature

-- 1. Upgrade 'profiles' table with social/personal fields
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS full_name TEXT,
ADD COLUMN IF NOT EXISTS avatar_url TEXT,
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS twitter_handle TEXT,
ADD COLUMN IF NOT EXISTS trading_style TEXT DEFAULT 'SCALPER'; -- SCALPER, SWING, HODL

-- 2. Create 'trade_journal' table for screenshots and notes
CREATE TABLE IF NOT EXISTS public.trade_journal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    symbol TEXT NOT NULL, -- e.g. BTC/USDT
    image_url TEXT, -- Supabase Storage URL
    notes TEXT,
    pnl_percent NUMERIC,
    trade_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. RLS Policies for Trade Journal
ALTER TABLE public.trade_journal ENABLE ROW LEVEL SECURITY;

-- Users can View their own journal
CREATE POLICY "Users can view own journal" 
    ON public.trade_journal FOR SELECT 
    USING ((select auth.uid()) = user_id);

-- Users can Insert into their own journal
CREATE POLICY "Users can insert own journal" 
    ON public.trade_journal FOR INSERT 
    WITH CHECK ((select auth.uid()) = user_id);

-- Users can Update/Delete their own journal
CREATE POLICY "Users can update own journal" 
    ON public.trade_journal FOR UPDATE 
    USING ((select auth.uid()) = user_id);

CREATE POLICY "Users can delete own journal" 
    ON public.trade_journal FOR DELETE 
    USING ((select auth.uid()) = user_id);

-- 4. Storage Bucket Policy (Conceptual - Setup via UI usually)
-- Bucket: 'trade-uploads'
-- Policy: Give Insert/Select access to Authenticated Users
