-- Enable Row Level Security (Recommended)
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- 1. Table: Market Signals (from Python Engine)
create table public.market_signals (
  id bigint generated by default as identity primary key,
  timestamp timestamptz default now(),
  symbol text not null,
  price numeric,
  rsi numeric,
  signal_type text not null, -- 'BUY', 'SELL', 'NEUTRAL'
  confidence int default 0,
  stop_loss numeric,  -- [NEW] Advice
  take_profit numeric, -- [NEW] Advice
  meta jsonb -- Extra data like volume, ema values
);

-- 2. Table: Market Sentiment (Fear & Greed cache)
create table public.market_sentiment (
  id bigint generated by default as identity primary key,
  timestamp timestamptz default now(),
  value int not null,
  classification text
);

-- 3. Enable Real-Time for these tables
alter publication supabase_realtime add table public.market_signals;
alter publication supabase_realtime add table public.market_sentiment;

-- 4. Policies (Public Read, Service Role Write)
alter table public.market_signals enable row level security;
create policy "Public Read Signals" on public.market_signals for select using (true);
create policy "Service Role Write Signals" on public.market_signals for insert with check (true); -- Requires Service Key

alter table public.market_sentiment enable row level security;
create policy "Public Read Sentiment" on public.market_sentiment for select using (true);
create policy "Service Role Write Sentiment" on public.market_sentiment for insert with check (true);
