-- Create error_logs table for system monitoring
CREATE TABLE IF NOT EXISTS error_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    service text,
    error_level text,
    message text
);

COMMENT ON TABLE error_logs IS 'System logs for Bot, Optimizer, and Scanner services';

-- Enable RLS to silence warnings and secure table
ALTER TABLE error_logs ENABLE ROW LEVEL SECURITY;

-- Allow all access for authenticated users (Service Role bypasses this, but good for Dashboard if needed)
CREATE POLICY "Allow Service Access" ON error_logs
    FOR ALL
    USING (true)
    WITH CHECK (true);
