-- Nexus AI Platform V2.5 - Database Schema Upgrade

-- 1. Table: Profiles (Linked to Supabase Auth)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamptz default now(),
  email text unique,
  full_name text,
  avatar_url text,
  is_waitlist boolean default true,
  role text default 'user' -- 'user', 'vips', 'admin'
);

-- Enable RLS for Profiles
alter table public.profiles enable row level security;
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- 2. Table: Error Logs (For Backend Monitoring)
create table if not exists public.error_logs (
  id bigint generated by default as identity primary key,
  timestamp timestamptz default now(),
  service text not null, -- 'scanner', 'trader', 'frontend'
  error_level text default 'ERROR', -- 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
  message text not null,
  stack_trace text,
  metadata jsonb
);

-- Enable RLS for Error Logs (Only Service Role/Admin can see, but public/everyone can write logs)
alter table public.error_logs enable row level security;
create policy "Service Role can insert logs" on public.error_logs for insert with check (true);
create policy "Admins can view logs" on public.error_logs for select using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- 3. Enhance Market Signals table
alter table public.market_signals 
add column if not exists volume_24h numeric,
add column if not exists confidence_score numeric,
add column if not exists atr_value numeric;

-- 4. Automatically create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 5. Real-time updates for profiles (for admin dashboards)
alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.error_logs;
