-- V40: Cosmos Oracle Schema
-- Stores real-time AI "Thoughts" (BLM) and high-frequency intelligence.

CREATE TABLE IF NOT EXISTS oracle_insights (
    id bigint generated by default as identity primary key,
    timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
    symbol text not null,
    timeframe text default '1m',
    trend_status text, -- "BULLISH", "BEARISH", "NEUTRAL"
    ai_probability numeric,
    reasoning text, -- The "Bot Language Model" insight string
    technical_context jsonb -- RSI, MACD, EMA values for record
);

COMMENT ON TABLE oracle_insights IS 'Real-time AI reasoning from the Cosmos Oracle BLM (V40)';

-- Enable RLS
ALTER TABLE oracle_insights ENABLE ROW LEVEL SECURITY;

-- Allow Public View (Dashboard)
CREATE POLICY "Allow Oracle View" ON oracle_insights
    FOR SELECT
    USING (true);

-- Allow Service Insert (Oracle Bot)
CREATE POLICY "Allow Oracle Insert" ON oracle_insights
    FOR INSERT
    TO authenticated, service_role
    WITH CHECK (true);

-- Retention Policy (Optional: Auto-cleanup old insights to save space)
-- This requires pg_cron or similar, but for now we will assume manual or dashboard limit
