-- V71: AI Model Registry
-- Tracks the performance and version of the local Cosmos AI brain in the hosted DB.

CREATE TABLE IF NOT EXISTS ai_model_registry (
    id bigint generated by default as identity primary key,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    version_tag text default 'v1.0.0',
    accuracy numeric, -- e.g. 0.82
    samples_trained integer,
    features_used text[], -- Array of feature names
    last_bootstrap_at timestamp with time zone,
    active boolean default true
);

COMMENT ON TABLE ai_model_registry IS 'Hosted registry for the locally-bootstrapped Cosmos AI state (V71)';

-- Enable RLS
ALTER TABLE ai_model_registry ENABLE ROW LEVEL SECURITY;

-- Allow Public View
CREATE POLICY "Allow Model View" ON ai_model_registry FOR SELECT USING (true);

-- Allow Service Insert/Update
CREATE POLICY "Allow Model Admin" ON ai_model_registry 
    FOR ALL 
    TO service_role 
    USING (true);

-- Ensure only one active model is tracked easily
CREATE OR REPLACE VIEW active_cosmos_brain AS
SELECT * FROM ai_model_registry WHERE active = true ORDER BY updated_at DESC LIMIT 1;

-- Add to Realtime
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE ai_model_registry;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END $$;
