-- V80: Multi-Asset Expansion (Top 20 Registry)
-- Description: Registers the top 20 liquid assets for the Cosmos AI to monitor.

CREATE TABLE IF NOT EXISTS market_assets (
    id bigint generated by default as identity primary key,
    symbol text unique not null,
    asset_name text,
    is_active boolean default true,
    added_at timestamp with time zone default timezone('utc'::text, now()) not null,
    last_scan_at timestamp with time zone,
    priority_score integer default 100 -- Higher = prioritized by AI
);

-- Seed with Top 20 Liquid Pairs (Kraken Format)
INSERT INTO market_assets (symbol, asset_name) VALUES
('BTC/USD', 'Bitcoin'),
('ETH/USD', 'Ethereum'),
('SOL/USD', 'Solana'),
('XRP/USD', 'Ripple'),
('ADA/USD', 'Cardano'),
('DOGE/USD', 'Dogecoin'),
('AVAX/USD', 'Avalanche'),
('DOT/USD', 'Polkadot'),
('LINK/USD', 'Chainlink'),
('MATIC/USD', 'Polygon'),
('SHIB/USD', 'Shiba Inu'),
('LTC/USD', 'Litecoin'),
('BCH/USD', 'Bitcoin Cash'),
('UNI/USD', 'Uniswap'),
('ATOM/USD', 'Cosmos'),
('XLM/USD', 'Stellar'),
('RENDER/USD', 'Render'),
('FIL/USD', 'Filecoin'),
('NEAR/USD', 'Near Protocol'),
('LDO/USD', 'Lido DAO')
ON CONFLICT (symbol) DO NOTHING;

-- Enable Realtime
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE market_assets;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END $$;

COMMENT ON TABLE market_assets IS 'Registry of the top 20 assets for Multi-Oracle monitoring (V80)';
