-- V90: Recursive AI Ranking Schema
-- Description: Stores the AI's live evaluation of all monitored assets.

CREATE TABLE IF NOT EXISTS ai_asset_rankings (
    id bigint generated by default as identity primary key,
    symbol text unique not null,
    score numeric, -- The AI Ranking Score (0-150+)
    confidence numeric, -- ML Probability
    trend_status text,
    reasoning text,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE ai_asset_rankings ENABLE ROW LEVEL SECURITY;

-- Allow Public View
CREATE POLICY "Allow Ranking View" ON ai_asset_rankings FOR SELECT USING (true);

-- Allow Service Upsert
CREATE POLICY "Allow Ranking Admin" ON ai_asset_rankings 
    FOR ALL 
    TO service_role 
    USING (true);

-- Add to Realtime Publication
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE ai_asset_rankings;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END $$;

COMMENT ON TABLE ai_asset_rankings IS 'Live AI evaluation of the top 20 crypto assets (V90)';
