
import os
from dotenv import load_dotenv
from supabase import create_client

load_dotenv(dotenv_path='../.env.local')
supabase = create_client(os.getenv("NEXT_PUBLIC_SUPABASE_URL"), os.getenv("SUPABASE_SERVICE_ROLE_KEY"))

sql = """
CREATE TABLE IF NOT EXISTS public.signal_audit_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT REFERENCES public.signals(id) ON DELETE CASCADE,
    symbol TEXT NOT NULL,
    signal_type TEXT NOT NULL, 
    entry_price NUMERIC NOT NULL,
    exit_price NUMERIC, 
    outcome TEXT CHECK (outcome IN ('WIN', 'LOSS', 'BREAKEVEN', 'PENDING')),
    pnl_percent NUMERIC, 
    max_drawdown_pct NUMERIC, 
    max_profit_pct NUMERIC, 
    duration_minutes INT,
    audit_timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.signal_audit_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Audit"
    ON public.signal_audit_history FOR SELECT
    USING (true);
    
-- Note: Service Write Policy is implicit with Service Role, but explicit policy helps if accessed via standard role with extra perms
"""

# Supabase-py doesn't support raw SQL execution easily without RPC.
# But we can try to use PostgREST RPC if a function exists, or we just rely on the user.
# ACTUALLY: We will assume we CANNOT run DDL via client here.
# User MUST run the SQL.

print("Please run audit_schema.sql in Supabase SQL Editor.")
